# Generated by Django 2.1.4 on 2018-12-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(db_column='Bookname', max_length=255, unique=True)),
                ('original_bookname', models.CharField(db_column='Original_Bookname', max_length=255)),
                ('genre', models.CharField(db_column='Genre', max_length=255)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('how_much_charter', models.IntegerField(db_column='How_much_charter')),
                ('how_much_translated', models.IntegerField(blank=True, db_column='How_much_translated', null=True)),
                ('translate_done', models.IntegerField(db_column='Translate_done')),
                ('date', models.DateTimeField(db_column='Date')),
                ('image', models.CharField(db_column='Image', max_length=500)),
            ],
            options={
                'db_table': 'Books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('page', models.IntegerField()),
            ],
            options={
                'db_table': 'Journal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='Username', max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(db_column='First_name', max_length=255)),
                ('second_name', models.CharField(db_column='Second_Name', max_length=255)),
            ],
            options={
                'db_table': 'Reader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transletors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='Username', max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, db_column='First_name', max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, db_column='Second_Name', max_length=255, null=True)),
                ('english_level', models.CharField(db_column='English_level', max_length=45)),
            ],
            options={
                'db_table': 'Transletors',
                'managed': False,
            },
        ),
    ]
